[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = ["cd frontend && npm ci"]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "cd frontend && npm run serve"

[variables]
NODE_ENV = "production"
PORT = "3000"
